name: MochiMochi
options:
  bundleIdPrefix: com.aamsellem
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""

targets:
  MochiMochi:
    type: application
    platform: macOS
    sources:
      - path: MochiMochi
        excludes:
          - "Resources/Skills/**"
      - path: MochiMochi/Resources/Skills
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aamsellem.mochi-mochi
        PRODUCT_NAME: Mochi Mochi
        INFOPLIST_FILE: MochiMochi/App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        COMBINE_HIDPI_IMAGES: YES
        CODE_SIGN_ENTITLEMENTS: MochiMochi/App/MochiMochi.entitlements
    entitlements:
      path: MochiMochi/App/MochiMochi.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true

  MochiMochiTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MochiMochiTests
    dependencies:
      - target: MochiMochi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aamsellem.mochi-mochi-tests
